ucenici = [
    {"prosek":4.2, "ime" : "Luka", "prezime" : "Kojovic"},
    {"prosek":3.9, "ime" : "Lazar", "prezime" : "Stefanovic"},
    {"prosek":3.5, "ime" : "Damjan", "prezime" : "Milenkovic"},
    {"prosek":4.6, "ime" : "Aleksa", "prezime" : "Marjanovic"},
    {"prosek":2.0, "ime" : "Luka", "prezime" : "Kulic"},
    {"prosek":3.1, "ime" : "Mihajlo", "prezime" : "Pusonja"},
    {"prosek":2.0, "ime" : "Jovan", "prezime": "Milinkovic"},
    {"prosek":4.6, "ime" : "Aleksa", "prezime": "Stefanovic"},
    {"prosek":4.0, "ime" : "Trifun", "prezime": "Bigic"},
    {"prosek":4.6, "ime" : "Dusan", "prezime": "Todorovic"},
    {"prosek" : 4.8, "ime" : "Sara", "prezime" : "Jovanovic"},
    {"prosek":4.5,"ime":"Sofija", "prezime":"Milic"},
    { "prosek": 4.7, "ime": "Jovan", "prezime": "Novokmet" },
    {"prosek":4.4, "ime": "Dusan", "prezime": "Parezanovic"},
    {"prosek":4.5, "ime" : "Aleksa", "prezime": "Stevanovic"},
]