ucenici = [
    {"odeljenje": "IV-SI-3", "prosek":4.2, "ime" : "Luka", "prezime" : "Kojovic"},
    {"odeljenje": "IV-SI-3", "prosek":3.9, "ime" : "Lazar", "prezime" : "Stefanovic"},
    {"odeljenje": "IV-SI-3","prosek":3.5, "ime" : "Damjan", "prezime" : "Milenkovic"},
    {"odeljenje": "IV-SI-3","prosek":4.6, "ime" : "Aleksa", "prezime" : "Marjanovic"},
    {"odeljenje": "IV-SI-3","prosek":2.0, "ime" : "Luka", "prezime" : "Kulic"},
    {"odeljenje": "IV-SI-3","prosek":3.1, "ime" : "Mihajlo", "prezime" : "Pusonja"},
    {"odeljenje": "IV-SI-3","prosek":2.0, "ime" : "Jovan", "prezime": "Milinkovic"},
    {"odeljenje": "IV-SI-3","prosek":4.6, "ime" : "Aleksa", "prezime": "Stefanovic"},
    {"odeljenje": "IV-SI-2","prosek":4.0, "ime" : "Trifun", "prezime": "Bigic"},
    {"odeljenje": "IV-SI-2","prosek":4.6, "ime" : "Dusan", "prezime": "Todorovic"},
    {"odeljenje": "IV-SI-2","prosek" : 4.8, "ime" : "Sara", "prezime" : "Jovanovic"},
    {"odeljenje": "IV-SI-2","prosek":4.5,"ime":"Sofija", "prezime":"Milic"},
    {"odeljenje": "IV-SI-2", "prosek": 4.7, "ime": "Jovan", "prezime": "Novokmet" },
    {"odeljenje": "IV-SI-2","prosek":4.4, "ime": "Dusan", "prezime": "Parezanovic"},
    {"odeljenje": "IV-SI-3","prosek":4.5, "ime" : "Aleksa", "prezime": "Stevanovic"},
    {"odeljenje": "IV-SI-3","prosek":4.9, "ime": "Kolja", "prezime": "Vasiljevic"},
    {"odeljenje": "IV-SI-3","prosek":4.9,"ime":"Nikolina","prezime":"Ivanovic"},
    {"odeljenje": "IV-SI-3","prosek":4.8, "ime": "Natalija", "prezime":"Mitrovic"},
    {"odeljenje": "IV-SI-3","prosek":4.7, "ime": "Marin", "prezime": "Boricic"},
    {"odeljenje": "IV-SI-3","prosek":4.5, "ime": "Anastasija", "prezime": "Milosevic"},
    {"odeljenje": "IV-SI-3","prosek":4.9, "ime": "Natalija", "prezime": "Djordjevic"},
    {"odeljenje": "IV-SI-3","prosek":4.8, "ime": "Mina", "prezime": "Milanovic"},
    {"odeljenje": "IV-SI-3","prosek":4.5, "ime": "Luka", "prezime": "Boricic"},

]