students = [
    {"class": "IV-SI-2","GPA":4.3,"name" : "Ivan", "surname" : "Petrovic"},
    {"class": "IV-SI-2", "GPA":4.1, "name" : "Luka", "surname" : "Jaksic"},
    {"class": "IV-SI-3", "GPA":4.2, "name" : "Luka", "surname" : "Kojovic"},
    {"class": "IV-SI-3", "GPA":3.9, "name" : "Lazar", "surname" : "Stefanovic"},
    {"class": "IV-SI-3","GPA":3.5, "name" : "Damjan", "surname" : "Milenkovic"},
    {"class": "IV-SI-3","GPA":4.6, "name" : "Aleksa", "surname" : "Marjanovic"},
    {"class": "IV-SI-3","GPA":2.0, "name" : "Luka", "surname" : "Kulic"},
    {"class": "IV-SI-3","GPA":3.1, "name" : "Mihajlo", "surname" : "Pusonja"},
    {"class": "IV-SI-3","GPA":2.0, "name" : "Jovan", "surname": "Milinkovic"},
    {"class": "IV-SI-3","GPA":4.6, "name" : "Aleksa", "surname": "Stefanovic"},
    {"class": "IV-SI-2","GPA":4.0, "name" : "Trifun", "surname": "Bigic"},
    {"class": "IV-SI-2","GPA":4.6, "name" : "Dusan", "surname": "Todorovic"},
    {"class": "IV-SI-2","GPA" : 4.8, "name" : "Sara", "surname" : "Jovanovic"},
    {"class": "IV-SI-2","GPA":4.5,"name":"Sofija", "surname":"Milic"},
    {"class": "IV-SI-2", "GPA": 4.7, "name": "Jovan", "surname": "Novokmet" },
    {"class": "IV-SI-2","GPA":4.4, "name": "Dusan", "surname": "Parezanovic"},
    {"class": "IV-SI-2","GPA":4.8, "name": "Pavle", "surname": "Ilic"},
    {"class": "IV-SI-3","GPA":4.5, "name" : "Aleksa", "surname": "Stevanovic"},
    {"class": "IV-SI-3","GPA":4.9, "name": "Kolja", "surname": "Vasiljevic"},
    {"class": "IV-SI-3","GPA":4.9,"name":"Nikolina","surname":"Ivanovic"},
    {"class": "IV-SI-3","GPA":4.8, "name": "Natalija", "surname":"Mitrovic"},
    {"class": "IV-SI-3","GPA":4.7, "name": "Marin", "surname": "Boricic"},
    {"class": "IV-SI-3","GPA":4.5, "name": "Anastasija", "surname": "Milosevic"},
    {"class": "IV-SI-3","GPA":4.9, "name": "Natalija", "surname": "Djordjevic"},
    {"class": "IV-SI-3","GPA":4.8, "name": "Mina", "surname": "Milanovic"},
    {"class": "IV-SI-3","GPA":4.5, "name": "Luka", "surname": "Boricic"},
    {"class": "IV-SI-2","GPA":5.0, "name": "Sara", "surname": "Radotic"},
    {"class": "IV-SI-2","GPA":4.9, "name": "Filip", "surname": "Slovic"},
]